package hr.fer.zemris.java.hw03.prob1;

/**
 * Represents possible {@code TokenTypes} generated by {@code Lexer}.
 * 
 * @author Filip Husnjak
 *
 */
public enum TokenType {
	
	EOF,
	
	WORD,
	
	NUMBER,
	
	SYMBOL
	
}
