package hr.fer.zemris.java.hw05.db.lexer;

/**
 * Represents possible types of a {@code QueryToken}
 * 
 * @author Filip Husnjak
 */
public enum QueryTokenType {

	/**
	 * Type of the last token generated by {@code QueryLexer}
	 */
	EOF,
		
	/**
	 * Tokens that hold words
	 */
	WORD,
	
	/**
	 * Tokens that begin and end with quotes
	 */
	STRING,
	
	/**
	 * Tokens that represent an array of symbols
	 */
	SYMBOLS
	
}
